VATSIM-UK/UK-Sector-File

- .github/Contributing.md
Line 57 - Added suggested ending to sentence.
Various - Added full-stops where perceived necessary.
N/A
> Contributing.md Changes Fixes #483

- .github/Contributing.md
Correcting the terminology from "_push_ request" to "_pull_ request"
N/A
> Fix #595 - correcting terminology

- .github/Contributing.md
Add reference to Good First Issue label
N/A
> Fixes #851 - Update Contribution Guide

- .github/CHANGELOG.md
- Doc/UK VATSIM frequencies.txt
Resolves #1184.
Updates documentation on Southend frequency differences
> Fixes #1184 - EGMC frequency update

- .github/PULL_REQUEST_TEMPLATE.md
> Add issue number field to Pull Request template

- .github/CHANGELOG.md
- Agreements/External/BUhigh_E.txt
Fixes #1930
Changed agreement from 280 to 290 (BULAM)
> Fixes #1930 - Corrected BUhigh->E Gatwick inbound agreement

- .github/CHANGELOG.md
- Colours.txt
Fixes #3421 
Landmass colour changed. Alt colours added as comment.
Nil
> Adjust Land Mass Colour Defintion

- .github/CHANGELOG.md
- Comments.txt
Fixes #3545 
As per the issue.
> Fixes #3545 - Corrects Comments.txt Department

- .github/workflows/compile.yml
Update the compiler to 1.6.0 and see if it breaks anything
> Update compiler to 1.6.0

- compiler.config.json
At the moment the new compiler STAR regex doesn't actually compile them in :(
Once this works a lot of other things can be made into regexes to save the hassle of adding things manually
> Get the compiler  STAR regex working

- .github/workflows/compile.yml
- compiler.config.json
Adds 'stars_airspace' for airports so it'll work again
> Update compiler to 1.8.0

- .github/workflows/compile.yml
> Update compiler to 1.10.2

- .gitignore
> Fix the gitignore to ignore output from the compiler

- .github/workflows/compile.yml
- .github/workflows/validate
> Validate-only on pull requests

- _data/SMR Files/EGBB/Old SMR/desktop.ini
- _data/SMR Files/EGBB/desktop.ini
- _data/SMR Files/EGBJ/desktop.ini
- _data/SMR Files/EGCC/Old (HS)/desktop.ini
- _data/SMR Files/EGCN/desktop.ini
- _data/SMR Files/EGGP/desktop.ini
- _data/SMR Files/EGJA/desktop.ini
- _data/SMR Files/EGJB/desktop.ini
- _data/SMR Files/EGJJ/desktop.ini
- _data/SMR Files/EGJJ/v1 (KH)/desktop.ini
- _data/SMR Files/EGJJ/v2 (SWRTS)/desktop.ini
- _data/SMR Files/EGKA/desktop.ini
- _data/SMR Files/EGKK/desktop.ini
- _data/SMR Files/EGLL/Old SMR/desktop.ini
- _data/SMR Files/EGLL/desktop.ini
- _data/SMR Files/EGMC/desktop.ini
- _data/SMR Files/EGMD/desktop.ini
- _data/SMR Files/EGNM/desktop.ini
- _data/SMR Files/EGNS/desktop.ini
- _data/SMR Files/EGNT/desktop.ini
- _data/SMR Files/EGSC/desktop.ini
- _data/SMR Files/EGSH/desktop.ini
- _data/SMR Files/EGTC/desktop.ini
Fixes #4507
Per issue. No changelog entry as shouldn't affect functionality of sector file in any way.
> Fixes #4507 - Delete the desktop.ini files

- .github/Contributing.md
Sample issue for the Sector File Webinar 2022
(please do not approve or merge)
> Correct spelling of amendments

- .github/Compiler Guide.md
- .gitignore
This is a guide to using the Compiler locally - comments on both usability of the guide and any grammar/spelling errors are appreciated.
#4416
> Create a guide to using the Compiler locally

- Comments.txt
- README.md
Fixes #5122
Per issue, licence added to readme and comments, no changelog entry required.
> Fixes #5122 - Add GPL v3 license

- .github/CHANGELOG.md
- .github/workflows/changelog police.yml
No longer shall @PLM1995 have to say changelog pls
Nil
> Automations - Check pull requests for changelog modification

- .github/workflows/compile.yml
Per https://github.com/actions/upload-artifact?tab=readme-ov-file#uploading-hidden-files
> Set new default flag to include hidden files for artifacts

- .github/workflows/release.yml
> Fix: Compiler Args for Release script

- .github/workflows/release.yml
> Revert euo Pipefail changes

- .github/workflows/release.yml
> Fix: file names

- .github/workflows/release.yml
> Fix: pass AIRAC date as env variable

- .github/workflows/release.yml
> Fix: more env fixes

- .github/workflows/release.yml
> Fix: SSH path

- .github/workflows/release.yml
> Fix: docs clone

- .github/workflows/release.yml
> Fix: Add debug logging
